site_name: Semantic Shift Detection
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.tabbed
    - content.image.figure
    - content.image.lightbox
    - content.image.zoom
    - content.video
    - content.iframe
    - content.math
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: lime
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: purple-grey
      accent: lime

plugins:
  - social
  - mkdocstrings
  - autorefs
  - search:
      lang: en
      tokenization: true
      terms: true
      stopwords: true
      filters:
        - lowercase
        - trim
        - stopword
        - stemmer
      engine: lunr
      index-page: true
      only-search-in-title: false
      start-page: true
      start-page-text: Start searching...
      


nav:
- Get Started:
  - Welcome to Semantic Shift Detection: index.md
#   - Why use Pydantic: why.md
#   - Help with Pydantic: help_with_pydantic.md
#   - Installation: install.md
#   - Migration Guide: migration.md
#   - Version Policy: version-policy.md
#   - Contributing: contributing.md
#   - Changelog: changelog.md
- Concepts:
  - Introduction: concepts/intro.md
#   - Models: concepts/models.md
#   - Fields: concepts/fields.md
#   - JSON Schema: concepts/json_schema.md
#   - Types: concepts/types.md
#   - Alias: concepts/alias.md
#   - Configuration: concepts/config.md
#   - Serialization: concepts/serialization.md
#   - Validators: concepts/validators.md
#   - Dataclasses: concepts/dataclasses.md
#   - Postponed Annotations: concepts/postponed_annotations.md
#   - Strict Mode: concepts/strict_mode.md
#   - Validation Decorator: concepts/validation_decorator.md
#   - Conversion Table: concepts/conversion_table.md
#   - Settings Management: concepts/pydantic_settings.md
#   - Performance: concepts/performance.md
#   - Pydantic Plugins: concepts/plugins.md
- Documentation:
  - Data: 
    - Load: doc/data/load.md
    - Preprocess: doc/data/preprocess.md
    - Graph Construction: doc/data/graph.md
  
  - Feature Extraction:
    - Word2Vec: doc/feature_extraction/word2vec.md
    - BERT: doc/feature_extraction/bert.md
    - RoBERTa: doc/feature_extraction/roberta.md
  
  - Requirements: requirements.md

#   - Pydantic:
#     - BaseModel: api/base_model.md
#     - RootModel: api/root_model.md
#     - Pydantic Dataclasses: api/dataclasses.md
#     - TypeAdapter: api/type_adapter.md
#     - Validation Decorator: api/validate_call.md
#     - Fields: api/fields.md
#     - Configuration: api/config.md
#     - JSON Schema: api/json_schema.md
#     - Errors: api/errors.md
#     - Functional Validators: api/functional_validators.md
#     - Functional Serializers: api/functional_serializers.md
#     - Standard Library Types: api/standard_library_types.md
#     - Pydantic Types: api/types.md
#     - Network Types: api/networks.md
#     - Version Information: api/version.md
#     - Pydantic Plugins: api/plugin.md
#     - Annotated Handlers: api/annotated_handlers.md
#   - Pydantic Core:
#     - pydantic_core: api/pydantic_core.md
#     - pydantic_core.core_schema: api/pydantic_core_schema.md
#   - Pydantic Settings: api/pydantic_settings.md
#   - Pydantic Extra Types:
#     - Color: api/pydantic_extra_types_color.md
#     - Country: api/pydantic_extra_types_country.md
#     - Payment: api/pydantic_extra_types_payment.md
#     - Phone Numbers: api/pydantic_extra_types_phone_numbers.md
#     - Routing Numbers: api/pydantic_extra_types_routing_numbers.md
#     - Coordinate: api/pydantic_extra_types_coordinate.md
#     - Mac Address: api/pydantic_extra_types_mac_address.md
# - Examples:
#   - Secrets: examples/secrets.md



extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/imene-swaan
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/imenekolli/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2023 <a href="https://www.linkedin.com/in/imenekolli/"  target="_blank" rel="noopener">Imene Kolli</a>
